<?php
/**
 * @category		Fishpig
 * @package		Fishpig_Wordpress
 * @license		http://fishpig.co.uk/license.txt
 * @author		Ben Tideswell <help@fishpig.co.uk>
 */
 ?>
<div class="content-header">
	<table cellspacing="0">
		<tbody>
			<tr>
				<td><h3 class="icon-head head-products"><?php echo Mage::helper('wordpress')->__('Custom Post Types') ?></h3></td>
			</tr>
		</tbody>
	</table>
</div>
<p>To use custom post types you will need the <a href="http://fishpig.co.uk/custom-post-types-inwordpress-integration.html?ref=mag" target="_blank">Custom Post Types</a> addon from FishPig.</p>